run.py
trainConversation.py
utils.py
workspaceParser.py

By applying exported workspace JSON as the training base, the candidate workspaces may use other metadata except the provided data, for example, dialog nodes, counter examples and so on.

Added workspace base for training

---

run.py

Pandas is able to parse the header in different encoding while `csv` module fails to do so.

Use pandas as csv parser for input validation

---

requirements.txt

Code update for #34 
Without `configparser` in my requirements.txt, or even in `pip list`, I was able to run the k-folds tool.  I assume it was pulled in from somewhere else.
For completeness I tested with installing `configparser-3.7.4`, the latest available when I ran `pip install configparser`

Add configparser

---

README.md
examples/intent-metrics.md

Documents the standalone usage of intentmetrics.py, also links it to the main README, as well as updating main README for IAM/URL configuration ala #30 / #46 

Issue #51: Documentation for intentmetrics tool

---

run.py
utils/__init__.py

Automatically runs those two utility reports after kfolds/blind.
Where 'outfile.csv' is created you now get 'outfile.csv.metrics.csv' and 'outfile.csv.confusion.csv'.

Issue #53 run metrics/confusion matrix after kfolds/blind

---

validate_workspace/validateWS.py

DCO 1.1 Signed-off-by: Leo Mazzoli <lmazzoli@us.ibm.com>
Updated the validateWA.py file to check for vgwCommands == None or len(vgwCommands) == 0 when checking for the existence of voice gateway commands.  
When there was an output section in the node response, but the node did NOT contain the vgwActionSequence, the vgwCommands list is coming back as empty (but not Null).

Check for empty vgwCommands list

---

config.ini.sample

DCO 1.1 Signed-off-by: Leo Mazzoli lmazzoli@us.ibm.com
Updated the config.ini.sample file to include required parameters for Blind testing.
previous_blind_out -- removed because it was optional
blind_figure_title -- added because it is required

Added blind testing parameters to sample config

---

README.md
extract_utterances/README.md
extract_utterances/getUtteranceBeforeNode.py

Connects to a workspace and extracts conversation "logs" matching a criteria then builds a report.
The criteria is a dialog node ID.
The report includes a list of user utterances immediately prior to accessing that dialog node (one utterance per conversation)
Solves #76 

Extract user utterances

---

config.ini.sample
examples/blind.md
examples/kfold.md
examples/long-tail-scoring.md
examples/standard-test.md
run.py
tests/test_workspaceParser.py
utils/__init__.py
utils/createPrecisionCurve.py
utils/testConversation.py
utils/trainConversation.py
utils/workspaceParser.py

Solves both #81 and #86 as they were easily coded and tested together.
The commits for each issue are kept separate for easier reviewing.
Almost all parameters in the "default" section are now made optional except for mode and workspace_id.  config.ini.sample shows additional legal parameters and their default values.
Most critically, the required values are all at the top and the optional values are below, there are no optional values 'above' required values thus making the file a bit easier to understand.
Blind/test "input" file is defaulted to `data/input.csv`, users are allowed and encouraged to provide alternate names.

Configuration enhancements: reduction of required and addition of API version

---

README.md
dialog_test/README.md
examples/confusion-matrix.md
examples/intent-description.md
examples/intent-metrics.md
examples/long-tail-scoring.md
extract_utterances/README.md
validate_workspace/README.md

Addresses #90 
Improves documentation for initial installation by pointing out need for Mac users to initialize SSL store.
Also clarifies python3 as supported runtime environment in the example commands.

Document initial setup of tool and suggest python3

---

config.ini.sample
dialog_test/README.md
dialog_test/flowtest.py
examples/blind.md
examples/intent-description.md
examples/kfold.md
examples/standard-test.md
run.py
tests/test_run.py
tests/test_testConversation.py
tests/test_trainConversation.py
tests/test_workspaceParser.py
utils/__init__.py
utils/get_intent_description.py
utils/testConversation.py
utils/trainConversation.py
utils/workspaceParser.py
validate_workspace/README.md
validate_workspace/validateWS.py

As of October 30, 2019 only IAM-based authentication will be allowed.
This pull request removes the basic authentication options completely from code and documentation, addressing Issue #100 .
I ran unit tests in six modes:
* kfold
* test
* blind
* validate_workspace
* get_intent_description
* flowtest

Remove username/password from code and documentation

---

validate_workspace/validateWS.py

DCO 1.1 Signed-off-by: Leo Mazzoli lmazzoli@us.ibm.com
Updated verifyNoDeadEnd logic to ignore nodes that are configured with Multi Conditional Responses.  Appears WA workspace structure had changed to identify these nodes in the metadata section.

#108 Ignore MCR Nodes

---

CHANGELOG.md
config.ini.sample
notebook_ws/WA-Testing-Tool-WS-Python-Notebook.ipynb
run.py

kfold output path is set by `test_output_path` same as the other modes.
Solves #123 

configurable kfold output path

---

validate_workspace/validateWS.py

Solves #136 .
Prints a warning for dialog nodes that check input.text directly.
ex:
```
WARN:   node_1_1549871256123    Directly checks 'input.text'. Consider using an entity or intent in the condition instead. Full condition text: ` (input.text == "Other" ||  input.text == "other")`
```

warn on nodes that check input.text directly

---

requirements.txt

Remove pandas version restriction

#138 Allow pandas 1.0.1 and higher, only 1.0.0 was broken

---

utils/createPrecisionCurve.py
utils/intentmetrics.py
utils/testConversation.py

1. Fixed the pandas deprecation warning on the default datatype
2. Fixed `ZeroDivisionError`  when calling `precision_recall_fscore_support` by making precision, recall, and f1 default to 0 when there are not any predicted true labels
3. Added extra error checking to avoid `ZeroDivisionError` when calculating individual precision, recall, and f1 scores. 
DCO 1.1 Signed-off-by: Pratyush Singh <pratyushsingh@ibm.com>

Precision & Recall Errors and Pandas Deprecation Fix

---

utils/testConversation.py

Edge-case to handle weird instances when the response returned by the Assistant is not always a string
The ` ' '.join(respone_text_list)` will fail if the items in the list are not type string. I encountered this edge case when running the notebook for the client, and they returned a blank dictionary, `{}`,  to the user (see attached). This is an issue that needs to be fixed at the client site, but added this extra check for robustness. 
DCO 1.1 Signed-off-by: Pratyush Singh <pratyushsingh@ibm.com>

Response returned by Watson Assistant isn't type string

---

requirements.txt
utils/createPrecisionCurve.py

Updated _requirements.txt_ file to install `scikit-learn > 0.22` to support the `zero_division` parameter in `precision_recall_fscore_support`. 
Also somehow the explicit datatype in `pd.Series()` in _createPrecisionCurve_ didn't make it through previously. I added that as well. 
DCO 1.1 Signed-off-by: Pratyush Singh <pratyushsingh@ibm.com>

Updated requirements.txt 

---

dialog_test/README.md
dialog_test/flowtest_v1.py

BEFORE:
* expected ouput is used as a regexp pattern. If an ouput specification
contains characters (e.g, `()`), tests fail even if the spec matches
the output character by character.
* multiline output make the TSV files very hard to work with, because a
record expands more than one row. Excel does not read it, and using an
editor is unintuitive because the columns are missaligned.
AFTER:
* the expected output is run through re.escape() before searching. This
behaviour is avoided if the specification is enclosed by forward slashes.
This can break backward compatibility for users that rely on the
undocumented fact that the the output specification was treated as a regexp
pattern instead of as a string
* multiline output specifications can use `<br>` instead of line breaks.
Output …

make use of regexp patterns explicit + friendlier multiline

---

CHANGELOG.md
utils/trainConversation.py

Solves #113 .  Thanks to @sueschm for the investigation!

Carry system settings to new workspace

---

log_analytics/extractConversations.py

Fixes #190 
`dialog_turn_counter` variable, and the entire `system` section, has moved in a recent WA log change.  Code is updated to handle new and old location.

#190 dialog_turn_counter variable has moved

---

log_analytics/extractConversations.py

Fixes #192 
Test new and old location of `nodes_visited` variable.

#192 test new and old nodes_visited location

---

log_analytics/extractConversations.py

Fixes #197 
Adds a column indicating if a message is the last turn in the conversation.

mark last turn of conversation

---

log_analytics/getAllLogs.py

Fixes #201 
Example progress:
```
afreed@andrews-mbp:[~/Code/WA-Testing-Tool/log_analytics] (master *)$ python getAllLogs.py -a <snipped> -l https://api.us-east.assistant.watson.cloud.ibm.com/instances/<snipped> -w <snipped> -n 2 -p 10 -f "request_timestamp>2021-10-01" -o test.json
Fetched 1 log pages with 10 total logs
Fetched 2 log pages with 20 total logs
Writing 20 logs to test.json
```

#201 status indicator during log fetch

---

utils/testConversation.py

Fixes #207 
Tested this on Python 3.7.4 but the warning seems to come from Python 3.9 or higher versions of dependent libraries than I have.  Would appreciate an additional tester.

fix deprecation warning on asyncio

---

config.ini.sample
run.py
utils/__init__.py
utils/choose_auth.py
utils/testConversation.py
utils/testNLC.py
utils/trainConversation.py
utils/trainNLC.py
utils/workspaceParser.py

Cloud Pak For Data (CP4D) uses a [slightly different authentication mechanism](https://cloud.ibm.com/apidocs/cloud-pak-data#getauthorizationtoken) than the standard IAM Token. This PR adds the [BearerTokenAuthenticator](https://github.com/IBM/python-sdk-core/blob/master/ibm_cloud_sdk_core/authenticators/bearer_token_authenticator.py) from ibm_cloud_sdk_core to support authentication via the user-based bearer token CP4D users can find in their instances' service details page.
This PR adds an `auth_type` key to the config.ini file, and `--auth-type` args to the commandline programs to choose between "bearer" and "iam" and uses the supplied `iam_apikey` as either the IAM key (default) or bearer token if "bearer" is specified.
Filed [Issue …

Add Cloud Pak For Data Authentication Support

---

log_analytics/README.md
log_analytics/extractConversations.py
log_analytics/getAllLogs.py

Addresses #215 for logs
Keeps existing APIs, uses intelligent in-place toggles to deal with v1 or v2 in same branches.
v2 log fetching requires a new argument, `environment_id`, which is tied to an Assistant and an Environment
Signed-off-by: Andrew R Freed <afreed@us.ibm.com>

#215 support for Actions-based logs

---

log_analytics/README.md
log_analytics/getAllLogs.py

Capability to get all logs related to a given conversation and export into transcript format.
* Tool already had ability to fetch logs for one conversation using filter string `-f "response.context.conversation_id::xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"`
* Added output format for transcript between user and Watson
* Added example in README

Export conversation in transcript format

---

log_analytics/extractConversations.py

Fixes #249 
Also appends `options` to the bot's output text.

shorten WA v2 action variables
