- CHANGELOG.md
- intent-description/README.md
- intent-description/get_intent_description.py
DCO 1.1 Signed-off-by: Alex Block amblock@us.ibm.com
Helper script to create an intent description csv file.
> intent description file

- testConversation.py
> Join all possible responses in the list

- CHANGELOG.md
- run.py
- testConversation.py
- trainConversation.py
- utils.py
- workspaceParser.py
Use a global constant in `utils.py` as base url.
> Made base url configurable

- CHANGELOG.md
- README.md
- config.ini.sample
- run.py
- workspaceParser.py
> Support local workspace JSON as training input

- dialog_test/README.md
- dialog_test/flowtest.py
- dialog_test/flowtest_v1.py
- dialog_test/tests/Customer_Care_Test.tsv
This code allows for users to automatically test their dialog flows within Watson Assistant using test files of expected behavior. For more information see the readme within this PR. Original code was created by Andrew Freed and adapted by me, Courtney Branson, for use here.
> Added automatic dialog testing files and sample test

- .gitignore
- utils/testConversation.py
Plus and Premium accounts bill by the user so it is important to pass all test calls as a single user.
Also included two small changes:
- Remove newline chars from utterance (Test was crashing if newline chars were included)
- print Exception instead of response on crashes (response does not exist if exception is caught)
> Pass user_id to WA

- validate_workspace/README.md
- validate_workspace/validateWS.py
Includes modes for:
* getting workspace via file or online connection
* validating SOE and/or IBM Voice Gateway syntax
> Initial workspace validation logic

- validate_workspace/validateWS.py
> Issue 44: Voice Gateway commands as of June 20 2019

- README.md
- config.ini.sample
- data/workspace_base.json
- requirements.txt
- run.py
- utils/__init__.py
- utils/testConversation.py
- utils/trainConversation.py
- utils/workspaceParser.py
This can be reviewed and merged with the master. I checked again and it appears the only few commits have been to the /dialog_test and not to the other files. I have the readme updated for instructions for configuring iam. Also note watson-developer-cloud==2.4.1
> iam support

- README.md
- config.ini.sample
- data/workspace_base.json
- requirements.txt
- run.py
- utils/__init__.py
- utils/testConversation.py
- utils/trainConversation.py
- utils/workspaceParser.py
Extends PR #37 and co-solves issue #30 by supporting both V1 and V2 levels of the installed SDK.
I checked out PR #37 and created this branch based on it.
Tested on both SDK 1.7.1 and 2.4.1
> Simultaneously support v1 and v2 level of API

- config.ini.sample
- run.py
- utils/__init__.py
- utils/testConversation.py
- utils/trainConversation.py
- utils/workspaceParser.py
- validate_workspace/validateWS.py
The url varies based on region the WA resource is created in.  The base url is now configurable in the same config.ini file used by the rest of the application.
Tested with Watson SDK 2.4.1 in kfold/blind/test mode.
> Issue 47 configurable base url

- examples/blind.md
- examples/kfold.md
- examples/standard-test.md
Depends on PR #48 / Issue #47 
The other dependency, PR #30/ PR #46 / Issue #30 was already merged.
> Update documentation to include configuration of IAM/URL

- examples/intent-metrics.md
- utils/intentmetrics.py
Implements #52 with simple print-out of f-score next to precision and recall
> Task 52 fscore metric

- README.md
- examples/confusion-matrix.md
- utils/confusionmatrix.py
Implements #29 with standard confusion matrix as provided by sklearn.
> 29 confusion matrix

- utils/workspaceParser.py
without it can fail in createTestTrainFolds.py on reading the .csv files generated here
> Fix encoding problems on windows

- README.md
- examples/long-tail-scoring.md
- utils/confusionmatrix.py
- utils/intentmetrics.py
- utils/longtailscoring.py
> Identify low-confidence responses for long-tail intent

- README.md
- config.ini.sample
- examples/kfold.md
Improve documentation inside the config file itself
> #74 add documentation to each parameter

- extract_utterances/getUtteranceBeforeNode.py
Bug found while testing additional workspaces.  Need safety checks on the intent extraction.
> #76 update in case of no intent detected

- utils/trainConversation.py
> #84 catch too many workspace error and advise on solution

- config.ini.sample
- examples/blind.md
- examples/kfold.md
- examples/long-tail-scoring.md
- examples/standard-test.md
- requirements.txt
- run.py
- tests/test_workspaceParser.py
- utils/__init__.py
- utils/createPrecisionCurve.py
- utils/createTestTrainFolds.py
- utils/testConversation.py
- utils/trainConversation.py
- utils/workspaceParser.py
Switched from watson_developer_cloud to ibm_watson - #82 
Updated get_values() function to_numpy(). - #83
DCO 1.1 Signed-off-by: Andrew Pang <apang@us.ibm.com>
> Updating IBM Libraries

- utils/createPrecisionCurve.py
Added set_ylim([0, 1.0]) for graph plot consistency 
https://github.com/cognitive-catalyst/WA-Testing-Tool/issues/41
DCO 1.1 Signed-off-by: Andrew Pang apang@us.ibm.com
> Hardcoding y-axis to 0-1.0

- config.ini.sample
- requirements.txt
- run.py
Defaulted to PNG output & updated requirements.txt to support JPG (added pillow lib)
#91
DCO 1.1 Signed-off-by: Andrew Pang apang@us.ibm.com
> Default png and jpg support

- README.md
- examples/kfold.md
Description of cross-validation score and explanation not to use it as single metric.
Addresses #101 
> Clarification on k-folds cross-validation

- notebook_ws/.gitignore
> Ignore local notebook save files

- validate_workspace/validateWS.py
Updated warning message for digression nodes.
Example:
```
WARN:	node_7_1234567890123	Does not play text, set an action, perform a jump and is not configured for MCR.  Inspect the digression settings in this node's ancestry to ensure it is not a dead-end node.
```
> #115 change dead-end test for digressions

- extract_utterances/README.md
- extract_utterances/getUtteranceBeforeNode.py
> 118 extract utterance logging mode

- CHANGELOG.md
- README.md
Added `git` instructions in README and updated CHANGELOG with 2019 events.
> documentation updates

- README.md
> Added link to dialog tester

- dialog_test/flowtest.py
> remove reference to deprecated package

- README.md
- examples/intent-metrics.md
- examples/kfold.md
- notebook_ws/WA-Testing-Tool-WS-Python-Notebook.ipynb
- utils/intentmetrics.py
Consolidate on precision/recall as per #127 
> Use precision/recall terminology

- requirements.txt
- utils/trainConversation.py
See #138 
Pandas 1.0 has a bug in `read_csv` flow, this PR temporarily restricts pandas version 1.0.0.  When Pandas 1.0.1 is released this bug should be fixed.
> Patch for pandas 1.0

- README.md
- config.ini.sample
- examples/blind.md
- examples/kfold.md
- examples/standard-test.md
Provide examples and explanation for new API endpoint
> 139 doc update new endpoints

- README.md
Update readme with detailed instructions for step 3 in the quick start.
> Update readme with detailed instructions

- validate_workspace/validateWS.py
* Add additional functions used when parsing WA workspaces
* Fix None condition when a dialog node has no conditions
> Add None check to input.text and additional reusable functions on Dialog/Workspace

- utils/intentmetrics.py
DCO 1.1 Signed-off-by:  Daniel J. Zyska <daniel.zyska@ibm.com>
intent scoring metrics remain unchanged
> #148 changed f-score def 4 treemap w partial cred

- log_analytics/getAllLogs.py
Making the getAllLogs.py script easier to consume.
> method documentation for getAllLogs.py

- log_analytics/extractConversations.py
DCO 1.1 Signed-off-by: Mohammad Gorji-Sefidmazgi <mgorjise@ibm.com>
> Fix the  extra "catch" condition

- dialog_test/flowtest.py
Fix #160 
DCO 1.1 Signed-off-by: Xavier Vergés xverges@gmail.com
> Return status of dialog flow tests #160

- dialog_test/flowtest.py
Fixed bug where WA_URL was set but not used.
> #164 use passed-in URL from user

- dialog_test/flowtest.py
Fix #161 
DCO 1.1 Signed-off-by: Xavier Vergés xverges@gmail.com
> Fix the JSON report on dialog flow tests

- dialog_test/README.md
- dialog_test/flowtest.py
- dialog_test/flowtest_v1.py
> #167 allow JSON or TSV input files

- utils/confusionmatrix.py
Copying Sue's DCO approval from title into description:
"DCO 1.1 Signed-off-by: Sue S Schmidt sueschm@us.ibm.com"
Andrew also contributed code.
> Fix warning on confusion matrix DCO 1.1 Signed-off-by: Sue S Schmidt sueschm@us.ibm.com

- log_analytics/extractConversations.py
Do not load all JSON contents into memory at once - load only one log file at a time.
> #185 extract from one file at a time

- log_analytics/extractConversations.py
Fix bug introduced #185 where custom field analytics were not applied to single log files.
> #186 single file parse needs custom fields too

- log_analytics/extractConversations.py
> #192 in case debug or nodes_visited is not present

- log_analytics/extractConversations.py
Added `filter()` which removes nulls
> #195 add filter to remove nulls

- log_analytics/extractConversations.py
> allow flexible input types

- log_analytics/extractConversations.py
> toggle CSV or PKL output

- run.py
- utils/testConversation.py
Fixes #205 
Add progress message after every 10 tested utterances.  Included messages for the beginning/end of training process as well.
> progress tracker for long-running tasks

- CHANGELOG.md
- README.md
- examples/compare-blind.md
- utils/compare_blind.py
> compare two blind test results

- log_analytics/README.md
- log_analytics/extractConversations.py
> phone log enhancements

- README.md
Signed-off-by: Andrew R Freed <afreed@us.ibm.com>
Fixes #217 
Add Medium articles, YouTube videos, and speech tooling links
> references to external education

- README.md
> clarify Python version needed for NLU

- log_analytics/ConversationAnalysisRecipes.ipynb
- log_analytics/extractConversations.py
- log_analytics/getAllLogs.py
Additional work for #215, specifically for users of the notebook (not the scripts directly)
Signed-off-by: Andrew R Freed <afreed@us.ibm.com>
> additional v2 updates for notebook users

- CHANGELOG.md
- README.md
- utils/testNLC.py
Fixes last part of #216 (caveat for older Python versions)
Signed-off-by: Andrew R Freed <afreed@us.ibm.com>
> fixed NLU mode for older Python versions

- utils/testConversation.py
> pass input columns to output file

- README.md
> Link to Dialog Skill analysis

- examples/confusion-matrix.md
- utils/confusionmatrix.py
> #240 global scaled option for confusion matrix

- utils/intentmetrics.py
> #242 store summary metrics to file

- utils/confusionmatrix.py
- utils/intentmetrics.py
> #235 optional sample weighting via 'weight' column

- log_analytics/extractConversations.py
> null safety for intent confidence

- log_analytics/getAllLogs.py
> #251 add BearerTokenAuthenticator for CP4D

- log_analytics/extractConversations.py
- requirements.txt
> support save to Excel file

- log_analytics/extractConversations.py
> add prev_output.text and reorder columns
